### ISSUE TITLE
Duplicate entry 

### ISSUE THREAD

**Issue by Danielle20** [WallaceFelipe/lamia-found#7]
Ao deletar um usuario,  nao consigo repetir em um novo cadastro os dados que deletei, nos campos de login e email. E ao deletar um projeto não consigo repetir num novo cadastro os dados que deletei, nos campos de código.

**Comment by pedroprado010** [comment]
Os usuários não são deletados do banco. De acordo com o doc. de requisitos eles são desativados, caso tentem acessar novamente a plataforma serão ativados, existe um campo na tabela exclusivo para isso.
